#!/bin/bash
clear

echo -e "##########Connecting to $database##########"
#cd ./Databases/"$database"

PS3="# $database,Choose an option:"

createTable="CreateTable";listTables="ListTables";dropTable="DropTable";insertInTable="InsertInTable"
selectFromTable="SelectFromTable";deleteFromTable="DeleteFromTable"

options=("$createTable"  "$listTables" "$dropTable" "$insertInTable" "$selectFromTable" "$deleteFromTable")


select choice in "${options[@]}"
do
        case $choice in
                $createTable)
                        # echo "create table"
                        source ./createTable
                        clear
                        ;;
                $listTables)
                        echo "list tables"
                        ;;
                $dropTable)
                        echo "drop table"
                        ;;
                $insertInTable)
                        #echo "insert in table"
			source ./insertInTable
                        ;;
                $selectFromTable)
                        echo "select from table"
                        ;;
                $deleteFromTable)
                        echo "delete from table"
                        ;;
                *)
                        echo "wrong choice"
                        ;;
        esac
done
